Number of Rounds: six
Total transactions: 1000 per round
Transaction Rates: 50, 100, 150, 200, 250, 300 TPS
Transaction mode: Write

test:
  name: add-hadith
  description: Benchmark for Hyperledger Fabric network using `AddHadith` function.
  workers:
    type: local
    number: 2
  rounds:
    - label: Round 1 - Add Hadith
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      workload:
        module: benchmarks/scenario/simple/pavan-v2.2/AddHadith.js
        arguments:
          assets: 50
    - label: Round 2 - Add Hadith
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: benchmarks/scenario/simple/pavan-v2.2/AddHadith.js
        arguments:
          assets: 100
    - label: Round 3 - Add Hadith
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 150
      workload:
        module: benchmarks/scenario/simple/pavan-v2.2/AddHadith.js
        arguments:
          assets: 150
    - label: Round 4 - Add Hadith
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: benchmarks/scenario/simple/pavan-v2.2/AddHadith.js
        arguments:
          assets: 200
    - label: Round 5 - Add Hadith
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 250
      workload:
        module: benchmarks/scenario/simple/pavan-v2.2/AddHadith.js
        arguments:
          assets: 250
    - label: Round 6 - Add Hadith
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 300
      workload:
        module: benchmarks/scenario/simple/pavan-v2.2/AddHadith.js
        arguments:
          assets: 300

# monitors:
#   resource:
#   - module: docker
#     options:
#       interval: 3
#       cpuUsageNormalization: true
#       containers:
#       - all