networks:
  test:

services:
  
  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    image: hyperledger/fabric-peer:2.5.0
    labels:
      service: hyperledger-fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_ADDRESS=peer1.org1.example.com:1052
      - CORE_PEER_LISTENADDRESS=0.0.0.0:1052
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.example.com:1053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:1053
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:1052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:1052


      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9445

        ## Enable TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp



      - CORE_PEER_LIMITS_CONCURRENCY_GATEWAYSERVICE=7000
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_EXECUTE_TIMEOUT=300s
      - CORE_PEER_KEEPALIVE_INTERVAL=60s

    ports:
      - 1052:1052
      - 9445:9445
    volumes:
      - ./channel/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com:/etc/hyperledger/fabric
      - /var/run/:/host/var/run/
    networks:
      - test
    deploy:
      resources:
        limits:
          cpus: '2.0'       # Limit the container to use at most 2 CPUs
          memory: '4G'      # Limit the container to use at most 4GB of memory
        reservations:
          cpus: '1.0'       # Reserve 1 CPU for the container
          memory: '2G'      # Reserve 2GB of memory for the container
